### PR TITLE
Update Pontoon logo

### LINKED ISSUE #946: Use the new Pontoon logo
Pontoon is getting a new logo and we should use it in the Add-on:
https://github.com/mozilla/pontoon/pull/3407

### PR DESCRIPTION
**Pull request by flodolo**
A few notes:
- The notification image is not updated, it doesn't seem to work from the Tour page.
- Some screenshots are now in Italian instead of Czech (tried to use at least English menus).
- I resized `toolbar-button.png` because it looked blurry on my system.

CC @mathjazz 

fix #946

### CODE REVIEW

**Comment by flodolo** [comment]
Additional note: this is only on stage for now, will be available at some point next week.

**Review by MikkCZ — APPROVED** [review]
Nice, screenshots looks fine, Czech is not important to be there. :)

Let me know when to merge and release new version with the new logo (or you can do so as well, it's all automated). The only thing that's not automated is the AMO and Chrome Web Store listings - those will need to updated independently.

**Comment by MikkCZ** [comment]
> The notification image is not updated, it doesn't seem to work from the Tour page.

It works for me currently on Linux, might be something system dependent? Either way, I finally got some time to update for manifest V3, for which I will be doing some more extensive testing on multiple browsers and hopefully multiple systems as well.

**Comment by flodolo** [comment]
> Let me know when to merge and release new version with the new logo (or you can do so as well, it's all automated). The only thing that's not automated is the AMO and Chrome Web Store listings - those will need to updated independently.

I'm out next week, so letting @mathjazz flag here when we're ready.

**Comment by flodolo** [comment]
> It works for me currently on Linux, might be something system dependent? Either way, I finally got some time to update for manifest V3, for which I will be doing some more extensive testing on multiple browsers and hopefully multiple systems as well.

That's on me, didn't realize macOS was hiding them 🤦🏼

**Review by mathjazz — APPROVED** [review]
Great work!

From my point of view, this is good to land and release in a new version.

**Comment by MikkCZ** [comment]
@mathjazz I am merging it then. Shall I also start publishing a new release now?

**Comment by mathjazz** [comment]
> @mathjazz I am merging it then.

Thanks!

> Shall I also start publishing a new release now?

Yup, go ahead!

**Comment by MikkCZ** [comment]
It's published and live in both AMO and Chrome Web Store. I will update the listings with the new logo and screenshots hopefully tomorrow.

**Pull request merged**
